### ISSUE TITLE
Pip Freeze

### ISSUE THREAD

**Issue by doohyunkwon** [jensengroup/ESNUEL_ML#1]
Hi Nicolai!

I'm excited to try out your new ESNUEL_ML based tool. Is it possible for you to run "pip freeze > requirements.txt" and upload the file here? I unfortunately don't have access to conda. I was able to get around this for ESNUEL, but having issues with ESNUEL_ML. I installed all the dependent packages, but the versioning is making it difficult to run. Here is the error below when running the example line from the readme.

`Traceback (most recent call last):
  File "/doo-hyun.kwon/code/ESNUEL_ML/src/esnuelML/predictor.py", line 59, in <module>
    nuc_RFmodel = load(os.path.join(base_dir, 'src/esnuelML/models/nuc/RF_SMI2GCS_3_cm5.joblib'))
  File "/doo-hyun.kwon/.pyenv/versions/esnuel-ml/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/doo-hyun.kwon/.pyenv/versions/esnuel-ml/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/doo-hyun.kwon/.pyenv/versions/3.9.17/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/doo-hyun.kwon/.pyenv/versions/esnuel-ml/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 402, in load_build
    Unpickler.load_build(self)
  File "/doo-hyun.kwon/.pyenv/versions/3.9.17/lib/python3.9/pickle.py", line 1717, in load_build
    setstate(state)
  File "_tree.pyx", line 867, in sklearn.tree._tree.Tree.__setstate__
  File "_tree.pyx", line 1573, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names':['left_child','right_child','feature','threshold','impurity','n_node_samples','weighted_n_node_samples','missing_go_to_left'], 'formats':['<i8','<i8','<i8','<f8','<f8','<i8','<f8','u1'], 'offsets':[0,8,16,24,32,40,48,56], 'itemsize':64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]`

Thanks very much!

**Comment by NicolaiRee** [comment]
Hi @doohyunkwon,
Again thank you for your comments and sorry for returning this late. However, I have added the requested pip freeze file to the repo. Please see: etc/requirements.txt
I hope this will help you with the installation!
Best wishes, Nicolai

**Comment by doohyunkwon** [comment]
Oops I forgot to reply here, no problem at all! Thank you for accommodating my requests @NicolaiRee!
